name: Github Actions
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - uses: jiro4989/setup-nim-action@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install hypothesis python-osc
    - run: nimble test -y
    - run: nimble test --gc:orc -y
    - run: nimble py -y
    - run: nimble pyproptest -y
